#!/usr/bin/env python3
"""
Form Page Test - Complete form interaction with detailed logging and screenshots
"""
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait, Select
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import TimeoutException, NoSuchElementException
import time
import os
import random
import string


def generate_test_data():
    """Generate random test data for form fields"""
    return {
        "first_name": f"Test{random.randint(100, 999)}",
        "last_name": f"User{random.randint(100, 999)}",
        "email": f"test.user{random.randint(1000, 9999)}@example.com",
        "phone": "03180743171",
        "company": f"Company{random.randint(1, 99)}",
        "password": "".join(random.choices(string.ascii_letters + string.digits, k=12)),
        "message": "This is a test message generated by automated testing script.",
        "address": f"{random.randint(100, 999)} Test Street",
        "city": "Pakistan",
        "zip_code": f"{random.randint(10000, 99999)}"
    }


def take_screenshot(driver, step_name, screenshot_dir):
    """Take a screenshot with timestamp"""
    timestamp = time.strftime("%Y%m%d_%H%M%S")
    filename = f"form_{step_name}_{timestamp}.png"
    path = os.path.join(screenshot_dir, filename)
    driver.save_screenshot(path)
    print(f"    📸 Screenshot: {filename}")
    return path


def log_step(step_number, description):
    """Log test steps with visual indicators"""
    print(f"\n{'═' * 60}")
    print(f"STEP {step_number}: {description}")
    print(f"{'═' * 60}")


def wait_for_element(driver, locator, timeout=10):
    """Wait for element to be visible"""
    try:
        element = WebDriverWait(driver, timeout).until(
            EC.visibility_of_element_located(locator)
        )
        return element
    except TimeoutException:
        print(f"    ⚠️  Timeout waiting for element: {locator}")
        return None


def run_test(driver):
    """
    Test: Form Page Interaction
    Tests a comprehensive form with various input types
    """
    try:
        # Setup
        screenshot_dir = "/app/output/screenshots"
        os.makedirs(screenshot_dir, exist_ok=True)
        test_data = generate_test_data()
        
        log_step(1, "INITIALIZING FORM TEST")
        print("🚀 Starting Form Page Test...")
        print(f"📊 Generated test data:")
        for key, value in test_data.items():
            print(f"    • {key}: {value}")

        # Navigate to form page (using a sample form page)
        print("\n📍 Navigating to form test page...")
        # You can use any of these form test URLs:
        # - "https://demoqa.com/automation-practice-form"
        # - "https://testpages.herokuapp.com/styled/basic-html-form-test.html"
        # - "https://www.w3schools.com/html/html_forms.asp"
        
        form_url = "https://demoqa.com/automation-practice-form"
        driver.get(form_url)
        take_screenshot(driver, "initial_load", screenshot_dir)

        # Wait for page load
        log_step(2, "WAITING FOR PAGE LOAD")
        print("⏳ Waiting for form to load...")
        WebDriverWait(driver, 15).until(
            EC.presence_of_element_located((By.TAG_NAME, "form"))
        )
        print("✅ Form loaded successfully")

        # Test form interaction
        log_step(3, "FILLING TEXT FIELDS")
        print("📝 Filling text inputs...")
        
        # Text input fields (adapt selectors based on actual form)
        text_fields = [
            {"name": "first_name", "selector": (By.ID, "firstName")},
            {"name": "last_name", "selector": (By.ID, "lastName")},
            {"name": "email", "selector": (By.ID, "userEmail")},
            {"name": "phone", "selector": (By.ID, "userNumber")},
        ]
        
        for field in text_fields:
            if field["name"] in test_data:
                element = wait_for_element(driver, field["selector"])
                if element:
                    element.clear()
                    element.send_keys(test_data[field["name"]])
                    print(f"    ✓ Filled {field['name']}: {test_data[field['name']]}")
                    take_screenshot(driver, f"filled_{field['name']}", screenshot_dir)
                    time.sleep(0.3)

        log_step(4, "SELECTING RADIO BUTTONS")
        print("🔘 Selecting gender...")
        try:
            # Example: Select gender radio button
            gender_radio = driver.find_element(By.XPATH, "//label[contains(text(),'Male')]")
            driver.execute_script("arguments[0].click();", gender_radio)
            print("    ✓ Selected gender: Male")
            take_screenshot(driver, "gender_selected", screenshot_dir)
        except Exception as e:
            print(f"    ⚠️  Could not select radio: {e}")

        log_step(5, "CHECKING CHECKBOXES")
        print("☑️  Checking checkboxes...")
        try:
            # Example: Select hobbies checkboxes
            hobbies = ["Sports", "Reading", "Music"]
            for hobby in hobbies[:2]:  # Select first 2
                try:
                    checkbox = driver.find_element(By.XPATH, f"//label[contains(text(),'{hobby}')]")
                    driver.execute_script("arguments[0].click();", checkbox)
                    print(f"    ✓ Checked: {hobby}")
                    time.sleep(0.2)
                except:
                    continue
            take_screenshot(driver, "checkboxes_selected", screenshot_dir)
        except Exception as e:
            print(f"    ⚠️  Could not select checkboxes: {e}")

        log_step(6, "SELECTING FROM DROPDOWNS")
        print("📋 Selecting from dropdowns...")
        try:
            # Example: Select state
            state_dropdown = driver.find_element(By.ID, "state")
            driver.execute_script("arguments[0].scrollIntoView();", state_dropdown)
            select = Select(state_dropdown)
            select.select_by_visible_text("NCR")
            print("    ✓ Selected state: NCR")
            take_screenshot(driver, "dropdown_selected", screenshot_dir)
        except Exception as e:
            print(f"    ⚠️  Could not select from dropdown: {e}")

        log_step(7, "UPLOADING FILE")
        print("📎 Uploading test file...")
        try:
            upload_input = driver.find_element(By.ID, "uploadPicture")
            # Create a dummy file to upload
            dummy_file = os.path.join(screenshot_dir, "test_upload.txt")
            with open(dummy_file, "w") as f:
                f.write("This is a test file for upload.")
            
            upload_input.send_keys(dummy_file)
            print(f"    ✓ Uploaded file: {dummy_file}")
            take_screenshot(driver, "file_uploaded", screenshot_dir)
        except Exception as e:
            print(f"    ⚠️  Could not upload file: {e}")

        log_step(8, "FILLING TEXTAREA")
        print("📄 Filling text area...")
        try:
            textarea = driver.find_element(By.ID, "currentAddress")
            textarea.send_keys(test_data["message"])
            print(f"    ✓ Filled text area with message")
            take_screenshot(driver, "textarea_filled", screenshot_dir)
        except Exception as e:
            print(f"    ⚠️  Could not fill textarea: {e}")

        log_step(9, "FORM VALIDATION CHECK")
        print("🔍 Validating form fields...")
        
        # Verify some fields have been filled
        verification_fields = ["firstName", "lastName", "userEmail"]
        all_valid = True
        
        for field_id in verification_fields:
            try:
                field = driver.find_element(By.ID, field_id)
                if field.get_attribute("value"):
                    print(f"    ✓ {field_id} is filled")
                else:
                    print(f"    ✗ {field_id} is empty")
                    all_valid = False
            except:
                print(f"    ? {field_id} not found")
        
        if all_valid:
            print("✅ All required fields are filled")
        else:
            print("⚠️  Some fields are not filled")

        log_step(10, "SUBMITTING FORM")
        print("🚀 Submitting form...")
        
        # Scroll to submit button
        submit_button = driver.find_element(By.ID, "submit")
        driver.execute_script("arguments[0].scrollIntoView({behavior: 'smooth', block: 'center'});", submit_button)
        time.sleep(1)
        take_screenshot(driver, "before_submit", screenshot_dir)
        
        print("    ⏳ Clicking submit button...")
        driver.execute_script("arguments[0].click();", submit_button)
        time.sleep(2)
        take_screenshot(driver, "after_submit", screenshot_dir)

        log_step(11, "CHECKING SUBMISSION RESULT")
        print("📊 Checking submission result...")
        time.sleep(3)
        
        try:
            # Look for success message or confirmation
            success_indicators = [
                "//*[contains(text(), 'Thanks for submitting')]",
                "//*[contains(text(), 'success')]",
                "//*[contains(text(), 'submitted')]",
                "//*[contains(@class, 'success')]",
                "//*[contains(@class, 'modal')]"
            ]
            
            success_found = False
            for xpath in success_indicators:
                try:
                    if driver.find_elements(By.XPATH, xpath):
                        print(f"    ✅ Found success indicator: {xpath}")
                        success_found = True
                        break
                except:
                    continue
            
            if success_found:
                print("🎉 FORM SUBMISSION SUCCESSFUL!")
            else:
                print("⚠️  No success message found, but continuing...")
                
            take_screenshot(driver, "submission_result", screenshot_dir)
            
        except Exception as e:
            print(f"    ⚠️  Could not verify submission: {e}")

        log_step(12, "FINAL VALIDATION")
        print("📋 Performing final checks...")
        
        # Check current URL
        current_url = driver.current_url
        print(f"    🌐 Current URL: {current_url}")
        
        # Check page title
        page_title = driver.title
        print(f"    📄 Page title: {page_title}")
        
        # Final screenshot
        final_screenshot = take_screenshot(driver, "final_state", screenshot_dir)
        print(f"\n📁 All screenshots saved to: {screenshot_dir}")
        
        # Generate summary report
        summary_file = os.path.join(screenshot_dir, "test_summary.txt")
        with open(summary_file, "w") as f:
            f.write("FORM TEST SUMMARY\n")
            f.write("=" * 50 + "\n")
            f.write(f"Test completed: {time.ctime()}\n")
            f.write(f"Test URL: {form_url}\n")
            f.write(f"Page title: {page_title}\n")
            f.write(f"Screenshots taken: {len([f for f in os.listdir(screenshot_dir) if f.endswith('.png')])}\n")
            f.write(f"Test data used:\n")
            for key, value in test_data.items():
                f.write(f"  {key}: {value}\n")
        
        print("\n" + "🎉" * 30)
        print("✅ FORM TEST COMPLETED SUCCESSFULLY!")
        print("📊 Summary:")
        print(f"   • Test data generated: {len(test_data)} fields")
        print(f"   • Screenshots captured: {len([f for f in os.listdir(screenshot_dir) if f.endswith('.png')])}")
        print(f"   • Form submitted: Yes")
        print(f"   • Final URL: {current_url}")
        print("🎉" * 30)
        
        return True

    except Exception as e:
        print(f"\n❌ TEST FAILED: {e}")
        import traceback
        traceback.print_exc()
        
        # Take screenshot of error state
        try:
            error_screenshot = os.path.join(screenshot_dir, "ERROR_final_state.png")
            driver.save_screenshot(error_screenshot)
            print(f"📸 Error screenshot saved: {error_screenshot}")
        except:
            pass
            
        return False


